version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install hatch
    - hatch run docs:build
    - mkdir -p $READTHEDOCS_OUTPUT
    - cp -r docs/_build/html $READTHEDOCS_OUTPUT
